version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run: docker pull ojford/texlive:latest

      - run: docker build --tag=texlive .

      - run:
         name: Test
         command: docker run texlive lualatex --version

      - run: docker save --output=texlive.tar texlive

      - save_cache:
          key: texlive-{{ .Revision }}
          paths:
            - texlive.tar

  push:
    machine: true

    steps:
      - checkout

      - restore_cache:
          key: texlive-{{ .Revision }}

      - run: docker load --input=texlive.tar

      - run:
          name: Tag & push if changed
          command: |
            docker pull ojford/texlive:latest
            current_sha="$(docker inspect --format='{{ .Id }}' ojford/texlive:latest)"
            if [ "$(docker inspect --format='{{ .Id }}' texlive)" != "$current_sha" ]; then
                docker tag texlive "ojford/texlive:$(date +'%Y-%M-%d')"
                docker tag texlive ojford/texlive:latest

                echo "$DOCKERHUB_PSWD" | docker login --username=ojfordci --password-stdin
                docker push ojford/texlive
            fi

workflows:
  version: 2

  workflow:
    jobs:
      - build

      - push:
          requires:
            - build
          filters:
            branches:
              only:
                - master

    triggers:
      - schedule:
          # Mondays at noon
          cron: 0 12 * * 1 
          filters:
            branches:
              only:
                - master
