name: Build & publish
on:
  push:
  schedule:
    # Mondays at noon
    - cron: 0 12 * * 1

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ojford
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ojford
          password: ${{ secrets.CR_PAT }}

      - name: Find current version date
        run: |
          docker pull ojford/texlive:latest
          current_sha="$(docker inspect --format='{{ .Id }}' ojford/texlive:latest)"
          echo "current_sha=$current_sha" > "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ojford/texlive:latest
            ghcr.io/ojford/texlive:latest

      - name: Push new dated version if updated
        run: |
          if [ "$(docker inspect --format='{{ .Id }}' texlive)" != "$current_sha" ]; then
            tag="$(date +'%Y-%m-%d')"
            docker tag texlive "ojford/texlive:$tag"
            docker tag texlive "ghcr.io/ojford/texlive:$tag"
            docker push "ojford/texlive:$tag"
            docker push "ghcr.io/ojford/texlive:$tag"
          fi
